<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>MEPL Icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resource\1234.jpg" />
    <None Remove="Resource\4321.jpg" />
    <None Remove="Resource\8765.jpg" />
    <None Remove="Resource\bg1.jpg" />
    <None Remove="Resource\bg2.jpg" />
    <None Remove="Resource\bg3.jpg" />
    <None Remove="Resource\generated-image.png" />
    <None Remove="Resource\Logo_ME.png" />
    <None Remove="Resource\valve.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="MEPL Icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.1" />
    <PackageReference Include="WPF-UI" Version="4.0.3" />
    <PackageReference Include="WPF-UI.DependencyInjection" Version="4.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resource\1234.jpg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resource\4321.jpg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resource\8765.jpg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resource\bg1.jpg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resource\bg2.jpg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resource\bg3.jpg">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resource\generated-image.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resource\Logo_ME.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resource\valve.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
